# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 06:24
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_interview', models.DateField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('interview_choice', models.CharField(choices=[('face_to_face', 'Face to Face'), ('telephonic', 'Telephonic')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_sent', models.NullBooleanField(default=False)),
                ('mail_sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sms_sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source_of_action', models.CharField(blank=True, choices=[('mail', 'E-Mail'), ('sms', 'SMS')], max_length=20, null=True)),
                ('time_of_action', models.DateTimeField(auto_now_add=True, null=True)),
                ('action_by_team_leader', models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('shortlisted', 'Shortlisted'), ('waiting', 'Put on Hold')], max_length=20, null=True)),
                ('action_by_recruiter', models.CharField(blank=True, choices=[('not_interested', 'Not Interested'), ('interested', 'Interested'), ('not_answered', 'Not Answered')], max_length=20, null=True)),
                ('is_shortlisted', models.NullBooleanField()),
                ('is_rejected', models.NullBooleanField()),
                ('mail_to_company', models.NullBooleanField()),
                ('mail_sent_to_shortlisted', models.NullBooleanField()),
                ('mail_sent_to_interested', models.NullBooleanField()),
            ],
            options={
                'ordering': ['-mail_sent_at', '-sms_sent_at', '-time_of_action'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='job_title', unique=True)),
                ('job_type', models.CharField(blank=True, choices=[('fulltime', 'Full Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('freelance', 'Freelance'), ('parttime', 'Part Time')], help_text='<strong>Select Type of job </strong>', max_length=10, null=True)),
                ('job_desc', models.TextField()),
                ('job_min_ctc', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('job_max_ctc', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True)),
                ('job_min_exp', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)])),
                ('job_max_exp', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)])),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_no_of_applications', models.IntegerField(blank=True, default=0)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-job_min_ctc'],
            },
        ),
        migrations.CreateModel(
            name='MailToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_sent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MailToShortlisted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to_shortlisted', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PreferredCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_sent', models.BooleanField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobListing')),
            ],
        ),
    ]
