# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('designation', '0001_initial'),
        ('jobseeker', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        ('jobs', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedcandidates',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.JobSeeker'),
        ),
        migrations.AddField(
            model_name='preferredcandidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobListing'),
        ),
        migrations.AddField(
            model_name='preferredcandidate',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.JobSeeker'),
        ),
        migrations.AddField(
            model_name='mailtoshortlisted',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobListing'),
        ),
        migrations.AddField(
            model_name='mailtoshortlisted',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobseeker.JobSeeker'),
        ),
        migrations.AddField(
            model_name='mailtocompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='mailtocompany',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.JobSeeker'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.ForeignKey(help_text='<strong>Select Company from dropdown', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_skills',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.Designation'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobListing'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseeker.JobSeeker'),
        ),
        migrations.AddField(
            model_name='interviewdetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='interviewdetail',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobListing'),
        ),
    ]
