# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20160803_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='mail_sent_to_interested',
            new_name='job_detail_sent_to_interested',
        ),
    ]
