# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160803_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplications',
            name='job_detail_sent_to_interested',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
