# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplications_job_detail_sent_to_interested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplications',
            name='job_detail_sent_to_interested',
        ),
    ]
